/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.alipay.android.app.sdk;

public final class R {
	public static final class color {
		public static final int TextColorBlack = 0x7f060000;
		public static final int TextColorGray = 0x7f060002;
		public static final int TextColorWhite = 0x7f060001;
		public static final int ToastBgColor = 0x7f060003;
		public static final int bgColor = 0x7f060008;
		public static final int btnColor = 0x7f060004;
		public static final int dialog_tiltle_blue = 0x7f06000e;
		public static final int downLoadBackFocus = 0x7f06000c;
		public static final int downLoadBackNomal = 0x7f06000b;
		public static final int downLoadBackPressed = 0x7f06000d;
		public static final int downLoadTextNomal = 0x7f060009;
		public static final int downLoadTextPressed = 0x7f06000a;
		public static final int secondbtntextColor = 0x7f060006;
		public static final int textColorforCheckBox = 0x7f060007;
		public static final int textColorforItemTitle = 0x7f060005;
	}
	public static final class drawable {
		public static final int dialog_bg_click = 0x7f0200d9;
		public static final int dialog_bg_normal = 0x7f0200da;
		public static final int dialog_button_colorlist = 0x7f0200dc;
		public static final int dialog_button_submit = 0x7f0200dd;
		public static final int dialog_cut_line = 0x7f0200de;
		public static final int dialog_split_h = 0x7f0200ec;
		public static final int dialog_split_v = 0x7f0200ed;
		public static final int popup_bg = 0x7f0201ca;
		public static final int refresh = 0x7f0201ed;
		public static final int refresh_button = 0x7f0201ee;
		public static final int refresh_push = 0x7f0201f0;
		public static final int title = 0x7f02028c;
		public static final int title_background = 0x7f02028e;
	}
	public static final class id {
		public static final int AlipayTitle = 0x7f0a01e8;
		public static final int btn_refresh = 0x7f0a01e9;
		public static final int dialog_button_group = 0x7f0a0211;
		public static final int dialog_content_view = 0x7f0a0210;
		public static final int dialog_divider = 0x7f0a020e;
		public static final int dialog_message = 0x7f0a020f;
		public static final int dialog_split_v = 0x7f0a0213;
		public static final int dialog_title = 0x7f0a020d;
		public static final int left_button = 0x7f0a0212;
		public static final int mainView = 0x7f0a01e7;
		public static final int right_button = 0x7f0a0214;
		public static final int webView = 0x7f0a00b7;
	}
	public static final class layout {
		public static final int alipay = 0x7f030058;
		public static final int alipay_title = 0x7f030059;
		public static final int dialog_alert = 0x7f03006c;
	}
	public static final class string {
		public static final int cancel = 0x7f070002;
		public static final int cancel_install_alipay = 0x7f070009;
		public static final int cancel_install_msp = 0x7f070008;
		public static final int confirm_title = 0x7f070000;
		public static final int content_description_icon = 0x7f070003;
		public static final int download = 0x7f070006;
		public static final int download_fail = 0x7f070007;
		public static final int ensure = 0x7f070001;
		public static final int install_alipay = 0x7f07000c;
		public static final int install_msp = 0x7f07000b;
		public static final int processing = 0x7f070005;
		public static final int redo = 0x7f07000a;
		public static final int refresh = 0x7f070004;
	}
	public static final class style {
		public static final int AlertDialog = 0x7f080002;
		public static final int AppBaseTheme = 0x7f080000;
		public static final int AppTheme = 0x7f080001;
	}
}
